// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Form: typeof import('./components/Form.vue')['default']
    FormProfile: typeof import('./components/FormProfile.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    'IMdi:delete': typeof import('~icons/mdi/delete')['default']
    'IMdi:edit': typeof import('~icons/mdi/edit')['default']
    'IMdi:fire': typeof import('~icons/mdi/fire')['default']
    IParkPlusCross: typeof import('~icons/icon-park/plus-cross')['default']
    ProfileViewMain: typeof import('./components/ProfileViewMain.vue')['default']
  }
}

export { }
